### ISSUE TITLE
We got the production down because of this, don't use it

### ISSUE THREAD

**Issue by awartani** [wgordon17/awesome-django-timezones#3]
```
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/sentry_sdk/integrations/django/middleware.py", line 134, in __call__
    return f(*args, **kwargs)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/sentry_sdk/integrations/django/middleware.py", line 90, in sentry_wrapped_method
    return old_method(*args, **kwargs)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/awesome_django_timezones/middleware.py", line 32, in __call__
    ip_info = ipapi.location(ip=get_ip_address(request), key=getattr(settings, 'DJANGO_IPAPI_KEY', None))
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/ipapi/ipapi.py", line 87, in location
    raise RateLimited(data)
ipapi.exceptions.RateLimited: {'error': True, 'reason': 'RateLimited', 'message': 'Visit https://ipapi.co/ratelimited/ for details'}
127.0.0.1 - - [31/Aug/2020:06:00:25 -0400] "POST /.............../ HTTP/1.0" 500 145 "-" ""

```

**Comment by ekerstein** [comment]
Looks like you were rate limited, how many ipapi requests did you send?
